# .github/workflows/frontend-checks.yml

name: Frontend Code Checks

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build-and-check:
    runs-on: ubuntu-latest # Use an Ubuntu virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # This step will clone your entire repository, including the 'meneer-app' folder
        # if it's part of your repo's structure.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x # Use a specific Node.js version, e.g., 20.x

      - name: Install Expo CLI (globally or locally)
        # This is generally a good idea for CI environments to ensure Expo tools are available
        run: |
          npm install -g eas-cli expo-cli

      - name: Navigate to frontend directory and install dependencies
        run: |
          cd meneer-app/ # IMPORTANT: This assumes 'meneer-app' is a subdirectory of your repo root
          npm install

      - name: Run Expo Doctor
        run: |
          cd meneer-app/ # IMPORTANT: Stay in the project directory
          npx expo doctor

      - name: Check for build readiness (optional - just simulates building)
        run: |
          echo "Simulating a build readiness check..."
          # As discussed, 'npx expo prebuild --no-install' could be added here
          # to check native module compatibility without triggering a full native build.
